version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    env_file: .env
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_PORT=$DB_PORT
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    restart: always
